name: Linter

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps: [
        {
            name: 'Checkout Code',
            uses: actions/checkout@v2
        },
        {
            name: 'Lint Code Base',
            uses: docker://github/super-linter:latest,
            env: {
                VALIDATE_ALL_CODEBASE: false
            }
        }]
