name: Linter

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps: [
        {
            name: 'Checkout Code',
            uses: actions/checkout@v2
            with:
              fetch-depth: 0
        },
        {
            name: 'Lint Code Base',
            uses: 'github/super-linter/slim@v4',
            env: {
                VALIDATE_ALL_CODEBASE: false,
                DEFAULT_BRANCH: 'master',
                GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
            }
        }]
