name: Trigger site rebuild

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps: [
        {
            name: 'Skip based on commit message',
            uses: veggiemonk/skip-commit@1.0.0,
            env: {
                COMMIT_FILTER: 'skip-ci'
            }
        },
        { name: 'Checkout Code', uses: actions/checkout@v2 },
        {
            name: 'Lint Code Base',
            uses: 'docker://github/super-linter:latest',
            env: {
                VALIDATE_ALL_CODEBASE: false,
                GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
            }
        },
        { name: 'Install Python', uses: actions/setup-python@v1, with: { python-version: 2.x, architecture: x64 } },
        { name: 'Install Requests', run: 'pip install --user requests' },
        { name: 'Update dates', run: 'python update.py --githubtoken=${{ secrets.SERVICES_GITHUB_TOKEN }} dates commit' },
        { name: 'Update stars', run: 'python update.py --githubtoken=${{ secrets.SERVICES_GITHUB_TOKEN }} starcount commit' },
        {
            name: 'Repository dispatch',
            uses: defold/repository-dispatch@1.2.1,
            with: {
                repo: 'defold/defold.github.io',
                token: '${{ secrets.SERVICES_GITHUB_TOKEN }}',
                user: 'services@defold.se',
                action: 'awesome'
            }
        }]
