name: Update stars

on:
    schedule:
        # hourly
        - cron: 0 */6 * * *

jobs:
    update_stars:

        runs-on: ubuntu-latest

        steps: [
            { name: 'Checkout', uses: actions/checkout@v2, with: { fetch-depth: 1 } },
            { name: 'Install Python', uses: actions/setup-python@v1, with: { python-version: 2.x, architecture: x64 } },
            { name: 'Install Requests', run: 'pip install --user requests' },
            { name: 'Update stars', run: 'python update.py --githubtoken=${{ secrets.SERVICES_GITHUB_TOKEN }} starcount commit' }]
